language: node_js
sudo: false
node_js:
- '10'
- '11'
install:
  # Remove purescript here once local installation is fixed.
  - npm install -g bower purescript
  - bower install --production
  - npm install
script:
  - npm run -s  build
  - npm run -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  node_modules/.bin/psc-publish > .pursuit.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @.pursuit.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
